version: "3"
services:
  gameyfin:
    image: grimsi/gameyfin:latest
    container_name: gameyfin
    environment:
      - GAMEYFIN_USER=<your username here>
      - GAMEYFIN_PASSWORD=<your password here>
      - GAMEYFIN_IGDB_API_CLIENT_ID=<your twitch client-id here>
      - GAMEYFIN_IGDB_API_CLIENT_SECRET=<your twitch client-secret here>
      - GAMEYFIN_SOURCES=/opt/gameyfin-library/library-1,/opt/gameyfin-library/library-2,/opt/gameyfin-library/library-3
    volumes:
      # Inside the first path, a ".gameyfin" directory will be created that will contain the metadata of all libraries
      # Therefore, you can specify an empty directory just to store the metadata.
      - <Path on your host to the 1st source folder>:/opt/gameyfin-library/library-1
      - <Path on your host to the 2nd source folder>:/opt/gameyfin-library/library-2
      - <Path on your host to the 3rd source folder>:/opt/gameyfin-library/library-3
    ports:
      - "8080:8080"
